### ISSUE TITLE
Bug - Heading adds “.00” after drawing permanent line

### ISSUE THREAD

**Issue by aidenbok203** [awdev1/Vector24#10]
https://github.com/user-attachments/assets/a2968b96-3fbb-400a-b258-2595e3d5f832

<img width="414" alt="image" src="https://github.com/user-attachments/assets/b2f38355-0f54-4a7d-b683-fda6dbf75bcc">

**Comment by aidenbok203** [comment]
@rishab-alt possibly a followup to your previous PR?

**Comment by rishab-alt** [comment]
> @rishab-alt possibly a followup to your previous PR?

I'll sort out when I'm free

**Comment by awdev1** [comment]
Fix being implemented to give @rishab-alt a bit of a break
