### ISSUE TITLE
MAC

### ISSUE THREAD

**Issue by aidenbok203** [awdev1/Vector24#23]
![Original_Mac_n_Cheese_](https://github.com/user-attachments/assets/3cfcd881-9dcb-442c-b214-cf523fe3a193)

**Comment by rishab-alt** [comment]
NO

**Comment by awdev1** [comment]
Support will be added soon for Mac, working on it.

**Comment by awdev1** [comment]
Almost done, testing now.

**Comment by JoseMoranUrena523** [comment]
The MacOS build is now available, but there are extra steps needed to run it.

1. Go to [https://github.com/awdev1/Vector24/actions](https://github.com/awdev1/Vector24/actions).
2. Press the latest one that says "Auto Compile on Commit (macOS)" on the bottom.
3. Scroll down and press "final-zip-package".
4. Once downloaded, unzip the files.
5. Right-click the folder, head to "Services" -> "New Terminal at Folder".
6. Type in "sh ./start.sh" (which will run the script which starts Vector24).

**Comment by aidenbok203** [comment]
> The MacOS build is now available, but there are extra steps needed to run it.
> 
> 1. Go to https://github.com/awdev1/Vector24/actions.
> 2. Press the latest one that says "Auto Compile on Commit (macOS)" on the bottom.
> 3. Scroll down and press "final-zip-package".
> 4. Once downloaded, unzip the files.
> 5. Right-click the folder, head to "Services" -> "New Terminal at Folder".
> 6. Type in "sh ./start.sh" (which will run the script which starts Vector24).

@JoseMoranUrena523 Hi Jose, can we compile that zip file as a release? It would probably be easier. Thanks.
