### ISSUE TITLE
Create issue/PR templates

### ISSUE THREAD

**Issue by Lucak1011** [awdev1/Vector24#28]
As per title.

**Comment by Lucak1011** [comment]
I'll work on this one

**Comment by aidenbok203** [comment]
@Lucak1011 Still working on it?

**Comment by Lucak1011** [comment]
> @Lucak1011 Still working on it?

I don't _think_ I'll be able to do it with any ease as I don't have repo access. I'll drop it for someone else.

**Comment by aidenbok203** [comment]
If you can’t do it I won’t be able to either

@awdev1 not sure if you can give repo access?
