### ISSUE TITLE
Bug - Line drawing below the cursor

### ISSUE THREAD

**Issue by aidenbok203** [awdev1/Vector24#7]
https://github.com/user-attachments/assets/30b9ed78-4157-412c-8455-f881826576f2

**Comment by AeroSD24** [comment]
Press OK, and it is fixed.

**Comment by aidenbok203** [comment]
still unintended, what if the user wants to read the guide while using

**Comment by AeroSD24** [comment]
Bug is non-critical and user can easily resolve it by pressing OK. Unlikely to cause real issues.

**Comment by AeroSD24** [comment]
Also - your driving a train. Keep your eyes on the rail!!

**Comment by awdev1** [comment]
Unable to replicate on 2 systems, closing.
